version: '3.8'
services:
  # Open WebUI - AI Chat Interface
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
      - DEFAULT_USER_ROLE=admin
      - ENABLE_SIGNUP=true
      - ENABLE_LOGIN_FORM=true
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - ai-network

  # Ollama - Local LLM Server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-network

  # Weaviate - Vector Database with GraphQL (Multimodal Support)
  weaviate:
    image: semitechnologies/weaviate:1.22.4
    container_name: weaviate
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai,img2vec-neural,multi2vec-clip,multi2vec-bind
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - ai-network

  # Document Processing Service (Optional)
  # This can help with document ingestion and processing
  document-processor:
    image: python:3.11-slim
    container_name: document-processor
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./document-processor:/app
      - ./documents:/app/documents
    command: >
      sh -c "pip install -r requirements.txt && python app.py"
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
    depends_on:
      - weaviate
    networks:
      - ai-network

volumes:
  open-webui-data:
  ollama-data:
  weaviate-data:

networks:
  ai-network:
    driver: bridge 