version: '3.8'
services:
  mcp:
    build: .
    container_name: mcp
    restart: unless-stopped
    environment:
      - OPEN_WEBUI_URL=http://host.docker.internal:3000
      - OPEN_WEBUI_API_KEY=your-webui-api-key
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app 