services:
  postgres: # Relational Database
    image: docker.io/postgres:${POSTGRES_VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    env_file:
      - ../../.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_VERSION=${POSTGRES_VERSION:-latest}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    networks:
      - homeserver-network

volumes:
  postgres_data: